In [2]:
import pandas as pd
import glob
import re

### 추가파일
- 지역코드
- 상병코드 (주상병, 부상병)

In [33]:
# 지역코드 csv 불러오기
sd = pd.read_csv('./1일차\\시도_지역코드.csv', encoding='EUC-KR')

# replace용 dic
# 변수명 row0, 2, 4, 6
i, j = 0, 2
for k in range(4):
    sd2 = sd.iloc[:, i:j].dropna()
    sd2 = sd2.astype({sd2.columns[0]:'int'})
    globals()['row{}'.format(i)]= dict(zip(sd2[sd2.columns[0]], sd2[sd2.columns[1]]))
    i += 2
    j += 2

In [4]:
# 상병코드 csv 불러오기
kcd = pd.read_csv('./1일차\\상병코드.csv', encoding='cp949')
kcd_dic = dict(zip(kcd.iloc[:,0], kcd.iloc[:,1]))

### 건강검진
- 변수명 : df1
- 파일개수 : 3
- copy : df11

In [37]:
# 건강검진 csv파일
df1 = pd.DataFrame()
for csv in glob.glob('./1일차/건강검진/*.CSV'):
    df1_temp = pd.read_csv(csv, encoding='EUC-KR')
    
    # 변수 삭제
    if '건강검진_2020' not in csv:
        df1_temp = df1_temp.drop(['데이터 공개일자', '결손치 유무', '치아마모증유무', '제3대구치(사랑니) 이상'], axis=1)
    else:
        df1_temp = df1_temp.drop(['데이터 공개일자'], axis=1)

    # 변수 정제
    df1_temp = df1_temp.replace({'시도코드':row0, '연령대 코드(5세단위)':row2, '성별코드':{1:'남자', 2:'여자'}})
    
    # df 합치기
    df1 = pd.concat([df1, df1_temp])

In [39]:
df1.to_csv('df1.csv', encoding='euc-kr', index=False)

In [6]:
display(df1.iloc[:, :15], df1.iloc[:, 15:])

,기준년도,가입자 일련번호,시도코드,성별코드,연령대 코드(5세단위),신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),청력(좌),청력(우),수축기 혈압,이완기 혈압,식전혈당(공복혈당)
0,2020,1,세종,남자,40~44세,165,60,72.1,1.2,1.5,1.0,1.0,127.0,79.0,90.0
1,2020,2,대구,여자,60~64세,150,65,81.0,0.8,0.8,1.0,1.0,110.0,73.0,87.0
2,2020,3,서울,여자,55~59세,155,55,70.0,0.6,0.7,1.0,1.0,123.0,80.0,102.0
3,2020,4,울산,남자,60~64세,160,70,90.8,1.0,1.0,1.0,2.0,134.0,84.0,146.0
4,2020,5,경기,여자,55~59세,155,50,75.2,1.5,1.2,1.0,1.0,144.0,89.0,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2020,999996,경기,여자,60~64세,145,55,81.0,0.9,1.0,1.0,1.0,132.0,78.0,124.0
999996,2020,999997,부산,여자,55~59세,160,55,76.5,1.5,1.5,1.0,1.0,100.0,64.0,98.0
999997,2020,999998,경남,남자,40~44세,175,70,85.0,1.2,1.2,1.0,1.0,110.0,64.0,83.0
999998,2020,999999,경남,여자,40~44세,160,70,91.0,0.6,0.5,1.0,1.0,137.0,82.0,111.0
999999,2020,1000000,인천,남자,50~54세,160,55,76.1,2.0,2.0,1.0,1.0,133.0,74.0,121.0

,총 콜레스테롤,트리글리세라이드,HDL 콜레스테롤,LDL 콜레스테롤,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석
0,188.0,58.0,58.0,118.0,15.0,1.0,1.1,21.0,27.0,21.0,1.0,0.0,0,NaN,NaN
1,NaN,NaN,NaN,NaN,12.7,1.0,0.5,18.0,15.0,15.0,1.0,0.0,0,NaN,NaN
2,NaN,NaN,NaN,NaN,12.8,1.0,0.7,27.0,25.0,7.0,1.0,0.0,0,NaN,NaN
3,NaN,NaN,NaN,NaN,16.4,1.0,1.2,65.0,97.0,72.0,1.0,0.0,1,0.0,0.0
4,220.0,171.0,53.0,133.0,12.4,1.0,0.7,18.0,17.0,14.0,1.0,0.0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,178.0,301.0,43.0,75.0,13.6,1.0,0.6,21.0,25.0,18.0,1.0,0.0,0,NaN,NaN
999996,288.0,93.0,71.0,198.0,14.0,1.0,0.8,21.0,14.0,19.0,1.0,1.0,0,NaN,NaN
999997,NaN,NaN,NaN,NaN,16.0,1.0,0.9,26.0,20.0,17.0,1.0,1.0,0,NaN,NaN
999998,208.0,113.0,59.0,126.0,11.9,1.0,1.0,25.0,29.0,13.0,1.0,0.0,0,NaN,NaN
999999,237.0,63.0,68.0,156.0,14.9,1.0,0.9,17.0,13.0,24.0,2.0,0.0,0,NaN,NaN

### 진료내역
##### 주상병코드 전체 알기위한 진료내역 전체 통합 df
- 변수명 : df2
- 파일개수 : 9
- copy : df22

In [8]:
# 진료내역 csv파일
df2 = pd.DataFrame()
for csv in glob.glob('./1일차/진료내역/*.CSV'):
    df2_temp = pd.read_csv(csv, encoding='EUC-KR')
    df2 = pd.concat([df2, df2_temp])

In [9]:
temp = []
temp2 = []
for val in list(df2['주상병코드'].value_counts().index):
    if re.findall(r'^[A-Z]_', val) != []:
        temp += re.findall(r'^[A-Z]_', val)
        temp2 += [re.sub(r'^[A-Z]_', val[0] + '00', val)]
kcd_dic1 = dict(zip(temp, temp2))

temp = []
temp2 = []
for val in list(df2['부상병코드'].value_counts().index):
    if re.findall(r'^[A-Z]_', val) != []:
        temp += re.findall(r'^[A-Z]_', val)
        temp2 += [re.sub(r'^[A-Z]_', val[0] + '00', val)]
kcd_dic2 = dict(zip(temp, temp2))

##### 데이터 변수 정제
- 변수명 : df22
- 변환 -> 통합

In [27]:
def Temp(csv):
    df2_temp = pd.read_csv(csv)
    
    # 변수명
    if '진료내역_2018' in csv:
        df2_temp = df2_temp.rename(columns={'가입자일련번호':'가입자 일련번호',
                                            '데이터기준일자':'데이터 기준일자'})
    
    # "달리 분류되지 않은" 코드 값 찾고 대체
    df2_temp = df2_temp.replace({'주상병코드':kcd_dic1, '부상병코드':kcd_dic2})
    
    # 상병코드 한글명 넣을 col
    df2_temp['주상병_한글명'] = df2_temp['주상병코드']
    df2_temp['부상병_한글명'] = df2_temp['부상병코드']
    
    # 데이터 정제
    df2_temp = df2_temp.replace({'시도코드':row0, '연령대코드':row2, '서식코드':row4, '진료과목코드':row6,
                                 '주상병_한글명':kcd_dic, '부상병_한글명':kcd_dic, '성별코드':{1:'남자', 2:'여자'}})
    
    # 데이터 기준일자 삭제
    df2_temp = df2_temp.drop('데이터 기준일자', axis=1)
    
    return df2_temp

In [28]:
df22 = pd.DataFrame()
for csv in glob.glob('./1일차/새 폴더/*.CSV'):
    df2_temp2 = Temp(csv)
    df22 = pd.concat([df22, df2_temp2])
    print('done.............')
df22

done.............
done.............
done.............

,기준년도,가입자 일련번호,진료내역일련번호,성별코드,연령대코드,시도코드,요양개시일자,서식코드,진료과목코드,주상병코드,부상병코드,요양일수,입내원일수,심결가산율,심결요양급여비용총액,심결본인부담금,심결보험자부담금,총처방일수,주상병_한글명,부상병_한글명
0,2020,29,3724043,남자,80~84세,경기,2020-12-21,의과 외래,내과,I109,E785,1,1,0.15,11540,1500,10040,0,고혈압(동맥성)(본태성)(원발성)(전신),상세불명의 고지질혈증
1,2020,29,3495225,남자,80~84세,경기,2020-12-14,의과 외래,내과,I109,E785,1,1,0.15,11540,1500,10040,7,고혈압(동맥성)(본태성)(원발성)(전신),상세불명의 고지질혈증
2,2020,255,10615350,여자,85세+,경기,2020-04-20,의과 외래,내과,I109,I251,1,1,0.15,11540,1500,10040,30,고혈압(동맥성)(본태성)(원발성)(전신),관상동맥 경화증
3,2020,255,10616553,여자,85세+,경기,2020-04-16,의과 외래,내과,I109,I251,1,1,0.15,11540,1500,10040,30,고혈압(동맥성)(본태성)(원발성)(전신),관상동맥 경화증
4,2020,2406,3105303,여자,80~84세,경기,2020-12-30,의과 외래,내과,I109,E780,1,1,0.15,11540,1500,10040,0,고혈압(동맥성)(본태성)(원발성)(전신),순수 고콜레스테롤혈증
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528955,2020,833610,4555037,여자,15~19세,경기,2020-11-05,의과 외래,내과,K291,J00,1,1,0.15,11540,3400,8140,3,기타 급성 위염,감염성 비염
528956,2020,833610,5316674,여자,15~19세,경기,2020-10-13,의과 외래,내과,K291,J00,1,1,0.15,11540,3400,8140,3,기타 급성 위염,감염성 비염
528957,2020,837565,1554838,남자,60~64세,전남,2020-01-06,의과 외래,내과,J209,J302,1,1,0.15,11540,3400,8140,3,상세불명의 급성 기관지염,기타 계절성 알레르기비염
528958,2020,837565,10940519,남자,60~64세,전남,2020-05-04,의과 외래,내과,J209,J302,1,1,0.15,11540,3400,8140,5,상세불명의 급성 기관지염,기타 계절성 알레르기비염
528959,2020,838595,10383322,여자,15~19세,울산,2020-04-29,의과 외래,내과,J0390,J00,1,1,0.15,11540,3400,8140,2,재발성으로 명시되어 있지 않은 궤양성 편도염(급성),감염성 비염

In [30]:
df22.to_csv('df22.csv', encoding = 'euc-kr', index=False)

In [32]:
display(df22.iloc[:5,:15], df22.iloc[:5, 15:])

,기준년도,가입자 일련번호,진료내역일련번호,성별코드,연령대코드,시도코드,요양개시일자,서식코드,진료과목코드,주상병코드,부상병코드,요양일수,입내원일수,심결가산율,심결요양급여비용총액
0,2020,29,3724043,남자,80~84세,경기,2020-12-21,의과 외래,내과,I109,E785,1,1,0.15,11540
1,2020,29,3495225,남자,80~84세,경기,2020-12-14,의과 외래,내과,I109,E785,1,1,0.15,11540
2,2020,255,10615350,여자,85세+,경기,2020-04-20,의과 외래,내과,I109,I251,1,1,0.15,11540
3,2020,255,10616553,여자,85세+,경기,2020-04-16,의과 외래,내과,I109,I251,1,1,0.15,11540
4,2020,2406,3105303,여자,80~84세,경기,2020-12-30,의과 외래,내과,I109,E780,1,1,0.15,11540

   심결본인부담금  심결보험자부담금  총처방일수                 주상병_한글명      부상병_한글명
0     1500     10040      0  고혈압(동맥성)(본태성)(원발성)(전신)  상세불명의 고지질혈증
1     1500     10040      7  고혈압(동맥성)(본태성)(원발성)(전신)  상세불명의 고지질혈증
2     1500     10040     30  고혈압(동맥성)(본태성)(원발성)(전신)     관상동맥 경화증
3     1500     10040     30  고혈압(동맥성)(본태성)(원발성)(전신)     관상동맥 경화증
4     1500     10040      0  고혈압(동맥성)(본태성)(원발성)(전신)  순수 고콜레스테롤혈증